server:
  port: 8080
dummyjson:
  api:
    url: https://dummyjson.com
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
  health:
    details:
      enabled: true